"""mensaje opcional

Revision ID: fb4e7a7eaf62
Revises: 
Create Date: 2025-10-20 23:09:04.047607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4e7a7eaf62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_car', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
